---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: aegis-system
type: Opaque
stringData:
  credentials.json: |
    {"AccountTag":"aff4ed64e72c1e215be1a4ba105e4ab1","TunnelSecret":"xKh5jtcRmVmmylq24XObs/boCkSGMmLB0LoEsP4rjqY=","TunnelID":"a21f6af6-e7b8-49d5-90be-08f0a8d9a829","Endpoint":""}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: aegis-system
data:
  config.yaml: |
    tunnel: a21f6af6-e7b8-49d5-90be-08f0a8d9a829
    credentials-file: /etc/cloudflared/creds/credentials.json

    ingress:
      - hostname: remote.aegis-platform.tech
        service: https://aegis-services-platform-api.aegis-system.svc.cluster.local:8081
        originRequest:
          noTLSVerify: true
          http2Origin: true
          disableChunkedEncoding: true
          connectTimeout: 30s
          keepAliveTimeout: 90s
      - hostname: keycloak.aegis-platform.tech
        service: https://aegis-services-keycloak-service.keycloak.svc.cluster.local:8443
        originRequest:
          noTLSVerify: true
          httpHostHeader: keycloak.aegis-platform.tech
          originServerName: keycloak.aegis-platform.tech
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: aegis-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - --loglevel
        - debug
        - run
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: config
        configMap:
          name: cloudflared-config
      - name: creds
        secret:
          secretName: cloudflared-credentials
