ALTER TABLE workloads ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMPTZ NULL;
ALTER TABLE workloads ADD COLUMN IF NOT EXISTS suspend_reason TEXT NULL;
ALTER TABLE workloads ADD COLUMN IF NOT EXISTS resume_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE workloads ADD COLUMN IF NOT EXISTS terminated_at TIMESTAMPTZ NULL;
ALTER TABLE workloads ADD COLUMN IF NOT EXISTS terminate_reason TEXT NULL;
