apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aegis-proxy-ingress
  namespace: default
  labels:
    app: aegis-auth-proxy
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /proxy
            pathType: Prefix
            backend:
              service:
                name: aegis-auth-proxy
                port:
                  number: 8080
