// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: aegis/v1/platform.proto

package aegisv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AegisPlatform_CreateProject_FullMethodName                 = "/aegis.v1.AegisPlatform/CreateProject"
	AegisPlatform_ListProjects_FullMethodName                  = "/aegis.v1.AegisPlatform/ListProjects"
	AegisPlatform_UpsertBudget_FullMethodName                  = "/aegis.v1.AegisPlatform/UpsertBudget"
	AegisPlatform_GetBudget_FullMethodName                     = "/aegis.v1.AegisPlatform/GetBudget"
	AegisPlatform_ListBudgets_FullMethodName                   = "/aegis.v1.AegisPlatform/ListBudgets"
	AegisPlatform_UpsertFlavor_FullMethodName                  = "/aegis.v1.AegisPlatform/UpsertFlavor"
	AegisPlatform_UpsertQueue_FullMethodName                   = "/aegis.v1.AegisPlatform/UpsertQueue"
	AegisPlatform_SubmitWorkload_FullMethodName                = "/aegis.v1.AegisPlatform/SubmitWorkload"
	AegisPlatform_GetWorkload_FullMethodName                   = "/aegis.v1.AegisPlatform/GetWorkload"
	AegisPlatform_ListWorkloads_FullMethodName                 = "/aegis.v1.AegisPlatform/ListWorkloads"
	AegisPlatform_CreateWorkspace_FullMethodName               = "/aegis.v1.AegisPlatform/CreateWorkspace"
	AegisPlatform_CreateCluster_FullMethodName                 = "/aegis.v1.AegisPlatform/CreateCluster"
	AegisPlatform_ImportCluster_FullMethodName                 = "/aegis.v1.AegisPlatform/ImportCluster"
	AegisPlatform_ListClusters_FullMethodName                  = "/aegis.v1.AegisPlatform/ListClusters"
	AegisPlatform_GetClusterJobStatus_FullMethodName           = "/aegis.v1.AegisPlatform/GetClusterJobStatus"
	AegisPlatform_GetWorkspaceConnectionDetails_FullMethodName = "/aegis.v1.AegisPlatform/GetWorkspaceConnectionDetails"
	AegisPlatform_CreateConnectionSession_FullMethodName       = "/aegis.v1.AegisPlatform/CreateConnectionSession"
	AegisPlatform_RenewConnectionSession_FullMethodName        = "/aegis.v1.AegisPlatform/RenewConnectionSession"
	AegisPlatform_RevokeConnectionSession_FullMethodName       = "/aegis.v1.AegisPlatform/RevokeConnectionSession"
	AegisPlatform_LeaseWorkload_FullMethodName                 = "/aegis.v1.AegisPlatform/LeaseWorkload"
	AegisPlatform_ListClusterWorkloadIDs_FullMethodName        = "/aegis.v1.AegisPlatform/ListClusterWorkloadIDs"
	AegisPlatform_StartWorkload_FullMethodName                 = "/aegis.v1.AegisPlatform/StartWorkload"
	AegisPlatform_AckWorkload_FullMethodName                   = "/aegis.v1.AegisPlatform/AckWorkload"
	AegisPlatform_RegisterCluster_FullMethodName               = "/aegis.v1.AegisPlatform/RegisterCluster"
	AegisPlatform_Heartbeat_FullMethodName                     = "/aegis.v1.AegisPlatform/Heartbeat"
	AegisPlatform_GetAwsClusterSignals_FullMethodName          = "/aegis.v1.AegisPlatform/GetAwsClusterSignals"
)

// AegisPlatformClient is the client API for AegisPlatform service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service
type AegisPlatformClient interface {
	CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	UpsertBudget(ctx context.Context, in *UpsertBudgetRequest, opts ...grpc.CallOption) (*Budget, error)
	GetBudget(ctx context.Context, in *GetBudgetRequest, opts ...grpc.CallOption) (*GetBudgetResponse, error)
	ListBudgets(ctx context.Context, in *ListBudgetsRequest, opts ...grpc.CallOption) (*ListBudgetsResponse, error)
	UpsertFlavor(ctx context.Context, in *UpsertFlavorRequest, opts ...grpc.CallOption) (*Flavor, error)
	UpsertQueue(ctx context.Context, in *UpsertQueueRequest, opts ...grpc.CallOption) (*Queue, error)
	SubmitWorkload(ctx context.Context, in *SubmitWorkloadRequest, opts ...grpc.CallOption) (*Workload, error)
	GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*Workload, error)
	ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error)
	CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*CreateWorkspaceResponse, error)
	CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error)
	ImportCluster(ctx context.Context, in *ImportClusterRequest, opts ...grpc.CallOption) (*ImportClusterResponse, error)
	ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error)
	GetClusterJobStatus(ctx context.Context, in *GetClusterJobStatusRequest, opts ...grpc.CallOption) (*GetClusterJobStatusResponse, error)
	GetWorkspaceConnectionDetails(ctx context.Context, in *GetWorkspaceConnectionDetailsRequest, opts ...grpc.CallOption) (*GetWorkspaceConnectionDetailsResponse, error)
	CreateConnectionSession(ctx context.Context, in *CreateConnectionSessionRequest, opts ...grpc.CallOption) (*ConnectionSession, error)
	RenewConnectionSession(ctx context.Context, in *RenewConnectionSessionRequest, opts ...grpc.CallOption) (*ConnectionSession, error)
	RevokeConnectionSession(ctx context.Context, in *RevokeConnectionSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	LeaseWorkload(ctx context.Context, in *LeaseWorkloadRequest, opts ...grpc.CallOption) (*LeaseWorkloadResponse, error)
	ListClusterWorkloadIDs(ctx context.Context, in *ListClusterWorkloadIDsRequest, opts ...grpc.CallOption) (*ListClusterWorkloadIDsResponse, error)
	StartWorkload(ctx context.Context, in *StartWorkloadRequest, opts ...grpc.CallOption) (*StartWorkloadResponse, error)
	AckWorkload(ctx context.Context, in *AckWorkloadRequest, opts ...grpc.CallOption) (*AckWorkloadResponse, error)
	RegisterCluster(ctx context.Context, in *ClusterRegisterRequest, opts ...grpc.CallOption) (*ClusterRegisterResponse, error)
	Heartbeat(ctx context.Context, in *ClusterHeartbeat, opts ...grpc.CallOption) (*ClusterHeartbeatAck, error)
	GetAwsClusterSignals(ctx context.Context, in *GetAwsSignalsRequest, opts ...grpc.CallOption) (*GetAwsSignalsResponse, error)
}

type aegisPlatformClient struct {
	cc grpc.ClientConnInterface
}

func NewAegisPlatformClient(cc grpc.ClientConnInterface) AegisPlatformClient {
	return &aegisPlatformClient{cc}
}

func (c *aegisPlatformClient) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...grpc.CallOption) (*Project, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Project)
	err := c.cc.Invoke(ctx, AegisPlatform_CreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) UpsertBudget(ctx context.Context, in *UpsertBudgetRequest, opts ...grpc.CallOption) (*Budget, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Budget)
	err := c.cc.Invoke(ctx, AegisPlatform_UpsertBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) GetBudget(ctx context.Context, in *GetBudgetRequest, opts ...grpc.CallOption) (*GetBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_GetBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) ListBudgets(ctx context.Context, in *ListBudgetsRequest, opts ...grpc.CallOption) (*ListBudgetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBudgetsResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_ListBudgets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) UpsertFlavor(ctx context.Context, in *UpsertFlavorRequest, opts ...grpc.CallOption) (*Flavor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Flavor)
	err := c.cc.Invoke(ctx, AegisPlatform_UpsertFlavor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) UpsertQueue(ctx context.Context, in *UpsertQueueRequest, opts ...grpc.CallOption) (*Queue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Queue)
	err := c.cc.Invoke(ctx, AegisPlatform_UpsertQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) SubmitWorkload(ctx context.Context, in *SubmitWorkloadRequest, opts ...grpc.CallOption) (*Workload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workload)
	err := c.cc.Invoke(ctx, AegisPlatform_SubmitWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*Workload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workload)
	err := c.cc.Invoke(ctx, AegisPlatform_GetWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_ListWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*CreateWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkspaceResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_CreateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) CreateCluster(ctx context.Context, in *CreateClusterRequest, opts ...grpc.CallOption) (*CreateClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClusterResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_CreateCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) ImportCluster(ctx context.Context, in *ImportClusterRequest, opts ...grpc.CallOption) (*ImportClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportClusterResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_ImportCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) ListClusters(ctx context.Context, in *ListClustersRequest, opts ...grpc.CallOption) (*ListClustersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClustersResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_ListClusters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) GetClusterJobStatus(ctx context.Context, in *GetClusterJobStatusRequest, opts ...grpc.CallOption) (*GetClusterJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterJobStatusResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_GetClusterJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) GetWorkspaceConnectionDetails(ctx context.Context, in *GetWorkspaceConnectionDetailsRequest, opts ...grpc.CallOption) (*GetWorkspaceConnectionDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkspaceConnectionDetailsResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_GetWorkspaceConnectionDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) CreateConnectionSession(ctx context.Context, in *CreateConnectionSessionRequest, opts ...grpc.CallOption) (*ConnectionSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionSession)
	err := c.cc.Invoke(ctx, AegisPlatform_CreateConnectionSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) RenewConnectionSession(ctx context.Context, in *RenewConnectionSessionRequest, opts ...grpc.CallOption) (*ConnectionSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionSession)
	err := c.cc.Invoke(ctx, AegisPlatform_RenewConnectionSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) RevokeConnectionSession(ctx context.Context, in *RevokeConnectionSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AegisPlatform_RevokeConnectionSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) LeaseWorkload(ctx context.Context, in *LeaseWorkloadRequest, opts ...grpc.CallOption) (*LeaseWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaseWorkloadResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_LeaseWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) ListClusterWorkloadIDs(ctx context.Context, in *ListClusterWorkloadIDsRequest, opts ...grpc.CallOption) (*ListClusterWorkloadIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClusterWorkloadIDsResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_ListClusterWorkloadIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) StartWorkload(ctx context.Context, in *StartWorkloadRequest, opts ...grpc.CallOption) (*StartWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkloadResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_StartWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) AckWorkload(ctx context.Context, in *AckWorkloadRequest, opts ...grpc.CallOption) (*AckWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckWorkloadResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_AckWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) RegisterCluster(ctx context.Context, in *ClusterRegisterRequest, opts ...grpc.CallOption) (*ClusterRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterRegisterResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_RegisterCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) Heartbeat(ctx context.Context, in *ClusterHeartbeat, opts ...grpc.CallOption) (*ClusterHeartbeatAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterHeartbeatAck)
	err := c.cc.Invoke(ctx, AegisPlatform_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisPlatformClient) GetAwsClusterSignals(ctx context.Context, in *GetAwsSignalsRequest, opts ...grpc.CallOption) (*GetAwsSignalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAwsSignalsResponse)
	err := c.cc.Invoke(ctx, AegisPlatform_GetAwsClusterSignals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AegisPlatformServer is the server API for AegisPlatform service.
// All implementations must embed UnimplementedAegisPlatformServer
// for forward compatibility.
//
// Service
type AegisPlatformServer interface {
	CreateProject(context.Context, *CreateProjectRequest) (*Project, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	UpsertBudget(context.Context, *UpsertBudgetRequest) (*Budget, error)
	GetBudget(context.Context, *GetBudgetRequest) (*GetBudgetResponse, error)
	ListBudgets(context.Context, *ListBudgetsRequest) (*ListBudgetsResponse, error)
	UpsertFlavor(context.Context, *UpsertFlavorRequest) (*Flavor, error)
	UpsertQueue(context.Context, *UpsertQueueRequest) (*Queue, error)
	SubmitWorkload(context.Context, *SubmitWorkloadRequest) (*Workload, error)
	GetWorkload(context.Context, *GetWorkloadRequest) (*Workload, error)
	ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error)
	CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*CreateWorkspaceResponse, error)
	CreateCluster(context.Context, *CreateClusterRequest) (*CreateClusterResponse, error)
	ImportCluster(context.Context, *ImportClusterRequest) (*ImportClusterResponse, error)
	ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error)
	GetClusterJobStatus(context.Context, *GetClusterJobStatusRequest) (*GetClusterJobStatusResponse, error)
	GetWorkspaceConnectionDetails(context.Context, *GetWorkspaceConnectionDetailsRequest) (*GetWorkspaceConnectionDetailsResponse, error)
	CreateConnectionSession(context.Context, *CreateConnectionSessionRequest) (*ConnectionSession, error)
	RenewConnectionSession(context.Context, *RenewConnectionSessionRequest) (*ConnectionSession, error)
	RevokeConnectionSession(context.Context, *RevokeConnectionSessionRequest) (*emptypb.Empty, error)
	LeaseWorkload(context.Context, *LeaseWorkloadRequest) (*LeaseWorkloadResponse, error)
	ListClusterWorkloadIDs(context.Context, *ListClusterWorkloadIDsRequest) (*ListClusterWorkloadIDsResponse, error)
	StartWorkload(context.Context, *StartWorkloadRequest) (*StartWorkloadResponse, error)
	AckWorkload(context.Context, *AckWorkloadRequest) (*AckWorkloadResponse, error)
	RegisterCluster(context.Context, *ClusterRegisterRequest) (*ClusterRegisterResponse, error)
	Heartbeat(context.Context, *ClusterHeartbeat) (*ClusterHeartbeatAck, error)
	GetAwsClusterSignals(context.Context, *GetAwsSignalsRequest) (*GetAwsSignalsResponse, error)
	mustEmbedUnimplementedAegisPlatformServer()
}

// UnimplementedAegisPlatformServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAegisPlatformServer struct{}

func (UnimplementedAegisPlatformServer) CreateProject(context.Context, *CreateProjectRequest) (*Project, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProject not implemented")
}
func (UnimplementedAegisPlatformServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedAegisPlatformServer) UpsertBudget(context.Context, *UpsertBudgetRequest) (*Budget, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertBudget not implemented")
}
func (UnimplementedAegisPlatformServer) GetBudget(context.Context, *GetBudgetRequest) (*GetBudgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBudget not implemented")
}
func (UnimplementedAegisPlatformServer) ListBudgets(context.Context, *ListBudgetsRequest) (*ListBudgetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBudgets not implemented")
}
func (UnimplementedAegisPlatformServer) UpsertFlavor(context.Context, *UpsertFlavorRequest) (*Flavor, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertFlavor not implemented")
}
func (UnimplementedAegisPlatformServer) UpsertQueue(context.Context, *UpsertQueueRequest) (*Queue, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertQueue not implemented")
}
func (UnimplementedAegisPlatformServer) SubmitWorkload(context.Context, *SubmitWorkloadRequest) (*Workload, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitWorkload not implemented")
}
func (UnimplementedAegisPlatformServer) GetWorkload(context.Context, *GetWorkloadRequest) (*Workload, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkload not implemented")
}
func (UnimplementedAegisPlatformServer) ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedAegisPlatformServer) CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*CreateWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkspace not implemented")
}
func (UnimplementedAegisPlatformServer) CreateCluster(context.Context, *CreateClusterRequest) (*CreateClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCluster not implemented")
}
func (UnimplementedAegisPlatformServer) ImportCluster(context.Context, *ImportClusterRequest) (*ImportClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportCluster not implemented")
}
func (UnimplementedAegisPlatformServer) ListClusters(context.Context, *ListClustersRequest) (*ListClustersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClusters not implemented")
}
func (UnimplementedAegisPlatformServer) GetClusterJobStatus(context.Context, *GetClusterJobStatusRequest) (*GetClusterJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterJobStatus not implemented")
}
func (UnimplementedAegisPlatformServer) GetWorkspaceConnectionDetails(context.Context, *GetWorkspaceConnectionDetailsRequest) (*GetWorkspaceConnectionDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkspaceConnectionDetails not implemented")
}
func (UnimplementedAegisPlatformServer) CreateConnectionSession(context.Context, *CreateConnectionSessionRequest) (*ConnectionSession, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConnectionSession not implemented")
}
func (UnimplementedAegisPlatformServer) RenewConnectionSession(context.Context, *RenewConnectionSessionRequest) (*ConnectionSession, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewConnectionSession not implemented")
}
func (UnimplementedAegisPlatformServer) RevokeConnectionSession(context.Context, *RevokeConnectionSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeConnectionSession not implemented")
}
func (UnimplementedAegisPlatformServer) LeaseWorkload(context.Context, *LeaseWorkloadRequest) (*LeaseWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaseWorkload not implemented")
}
func (UnimplementedAegisPlatformServer) ListClusterWorkloadIDs(context.Context, *ListClusterWorkloadIDsRequest) (*ListClusterWorkloadIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClusterWorkloadIDs not implemented")
}
func (UnimplementedAegisPlatformServer) StartWorkload(context.Context, *StartWorkloadRequest) (*StartWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorkload not implemented")
}
func (UnimplementedAegisPlatformServer) AckWorkload(context.Context, *AckWorkloadRequest) (*AckWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckWorkload not implemented")
}
func (UnimplementedAegisPlatformServer) RegisterCluster(context.Context, *ClusterRegisterRequest) (*ClusterRegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterCluster not implemented")
}
func (UnimplementedAegisPlatformServer) Heartbeat(context.Context, *ClusterHeartbeat) (*ClusterHeartbeatAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAegisPlatformServer) GetAwsClusterSignals(context.Context, *GetAwsSignalsRequest) (*GetAwsSignalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAwsClusterSignals not implemented")
}
func (UnimplementedAegisPlatformServer) mustEmbedUnimplementedAegisPlatformServer() {}
func (UnimplementedAegisPlatformServer) testEmbeddedByValue()                       {}

// UnsafeAegisPlatformServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AegisPlatformServer will
// result in compilation errors.
type UnsafeAegisPlatformServer interface {
	mustEmbedUnimplementedAegisPlatformServer()
}

func RegisterAegisPlatformServer(s grpc.ServiceRegistrar, srv AegisPlatformServer) {
	// If the following call panics, it indicates UnimplementedAegisPlatformServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AegisPlatform_ServiceDesc, srv)
}

func _AegisPlatform_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_CreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).CreateProject(ctx, req.(*CreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_UpsertBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).UpsertBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_UpsertBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).UpsertBudget(ctx, req.(*UpsertBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_GetBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).GetBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_GetBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).GetBudget(ctx, req.(*GetBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_ListBudgets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBudgetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).ListBudgets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_ListBudgets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).ListBudgets(ctx, req.(*ListBudgetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_UpsertFlavor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertFlavorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).UpsertFlavor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_UpsertFlavor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).UpsertFlavor(ctx, req.(*UpsertFlavorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_UpsertQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).UpsertQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_UpsertQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).UpsertQueue(ctx, req.(*UpsertQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_SubmitWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).SubmitWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_SubmitWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).SubmitWorkload(ctx, req.(*SubmitWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_GetWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).GetWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_GetWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).GetWorkload(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_ListWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).ListWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_ListWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).ListWorkloads(ctx, req.(*ListWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_CreateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).CreateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_CreateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).CreateWorkspace(ctx, req.(*CreateWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_CreateCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).CreateCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_CreateCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).CreateCluster(ctx, req.(*CreateClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_ImportCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).ImportCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_ImportCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).ImportCluster(ctx, req.(*ImportClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_ListClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).ListClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_ListClusters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).ListClusters(ctx, req.(*ListClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_GetClusterJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).GetClusterJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_GetClusterJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).GetClusterJobStatus(ctx, req.(*GetClusterJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_GetWorkspaceConnectionDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceConnectionDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).GetWorkspaceConnectionDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_GetWorkspaceConnectionDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).GetWorkspaceConnectionDetails(ctx, req.(*GetWorkspaceConnectionDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_CreateConnectionSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConnectionSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).CreateConnectionSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_CreateConnectionSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).CreateConnectionSession(ctx, req.(*CreateConnectionSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_RenewConnectionSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewConnectionSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).RenewConnectionSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_RenewConnectionSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).RenewConnectionSession(ctx, req.(*RenewConnectionSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_RevokeConnectionSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeConnectionSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).RevokeConnectionSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_RevokeConnectionSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).RevokeConnectionSession(ctx, req.(*RevokeConnectionSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_LeaseWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaseWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).LeaseWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_LeaseWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).LeaseWorkload(ctx, req.(*LeaseWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_ListClusterWorkloadIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClusterWorkloadIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).ListClusterWorkloadIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_ListClusterWorkloadIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).ListClusterWorkloadIDs(ctx, req.(*ListClusterWorkloadIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_StartWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).StartWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_StartWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).StartWorkload(ctx, req.(*StartWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_AckWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).AckWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_AckWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).AckWorkload(ctx, req.(*AckWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_RegisterCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).RegisterCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_RegisterCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).RegisterCluster(ctx, req.(*ClusterRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).Heartbeat(ctx, req.(*ClusterHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisPlatform_GetAwsClusterSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAwsSignalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisPlatformServer).GetAwsClusterSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisPlatform_GetAwsClusterSignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisPlatformServer).GetAwsClusterSignals(ctx, req.(*GetAwsSignalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AegisPlatform_ServiceDesc is the grpc.ServiceDesc for AegisPlatform service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AegisPlatform_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.v1.AegisPlatform",
	HandlerType: (*AegisPlatformServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProject",
			Handler:    _AegisPlatform_CreateProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _AegisPlatform_ListProjects_Handler,
		},
		{
			MethodName: "UpsertBudget",
			Handler:    _AegisPlatform_UpsertBudget_Handler,
		},
		{
			MethodName: "GetBudget",
			Handler:    _AegisPlatform_GetBudget_Handler,
		},
		{
			MethodName: "ListBudgets",
			Handler:    _AegisPlatform_ListBudgets_Handler,
		},
		{
			MethodName: "UpsertFlavor",
			Handler:    _AegisPlatform_UpsertFlavor_Handler,
		},
		{
			MethodName: "UpsertQueue",
			Handler:    _AegisPlatform_UpsertQueue_Handler,
		},
		{
			MethodName: "SubmitWorkload",
			Handler:    _AegisPlatform_SubmitWorkload_Handler,
		},
		{
			MethodName: "GetWorkload",
			Handler:    _AegisPlatform_GetWorkload_Handler,
		},
		{
			MethodName: "ListWorkloads",
			Handler:    _AegisPlatform_ListWorkloads_Handler,
		},
		{
			MethodName: "CreateWorkspace",
			Handler:    _AegisPlatform_CreateWorkspace_Handler,
		},
		{
			MethodName: "CreateCluster",
			Handler:    _AegisPlatform_CreateCluster_Handler,
		},
		{
			MethodName: "ImportCluster",
			Handler:    _AegisPlatform_ImportCluster_Handler,
		},
		{
			MethodName: "ListClusters",
			Handler:    _AegisPlatform_ListClusters_Handler,
		},
		{
			MethodName: "GetClusterJobStatus",
			Handler:    _AegisPlatform_GetClusterJobStatus_Handler,
		},
		{
			MethodName: "GetWorkspaceConnectionDetails",
			Handler:    _AegisPlatform_GetWorkspaceConnectionDetails_Handler,
		},
		{
			MethodName: "CreateConnectionSession",
			Handler:    _AegisPlatform_CreateConnectionSession_Handler,
		},
		{
			MethodName: "RenewConnectionSession",
			Handler:    _AegisPlatform_RenewConnectionSession_Handler,
		},
		{
			MethodName: "RevokeConnectionSession",
			Handler:    _AegisPlatform_RevokeConnectionSession_Handler,
		},
		{
			MethodName: "LeaseWorkload",
			Handler:    _AegisPlatform_LeaseWorkload_Handler,
		},
		{
			MethodName: "ListClusterWorkloadIDs",
			Handler:    _AegisPlatform_ListClusterWorkloadIDs_Handler,
		},
		{
			MethodName: "StartWorkload",
			Handler:    _AegisPlatform_StartWorkload_Handler,
		},
		{
			MethodName: "AckWorkload",
			Handler:    _AegisPlatform_AckWorkload_Handler,
		},
		{
			MethodName: "RegisterCluster",
			Handler:    _AegisPlatform_RegisterCluster_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AegisPlatform_Heartbeat_Handler,
		},
		{
			MethodName: "GetAwsClusterSignals",
			Handler:    _AegisPlatform_GetAwsClusterSignals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aegis/v1/platform.proto",
}
