// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: aegis/v1/platform.proto

package aegisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---- Core resource messages ----
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	OwnerGroup    string                 `protobuf:"bytes,3,opt,name=owner_group,json=ownerGroup,proto3" json:"owner_group,omitempty"`
	Policy        *PolicyDomain          `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_aegis_v1_platform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Project) GetOwnerGroup() string {
	if x != nil {
		return x.OwnerGroup
	}
	return ""
}

func (x *Project) GetPolicy() *PolicyDomain {
	if x != nil {
		return x.Policy
	}
	return nil
}

type PolicyDomain struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Regions             []string               `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	DataLevel           string                 `protobuf:"bytes,2,opt,name=data_level,json=dataLevel,proto3" json:"data_level,omitempty"`
	DenyEgressByDefault bool                   `protobuf:"varint,3,opt,name=deny_egress_by_default,json=denyEgressByDefault,proto3" json:"deny_egress_by_default,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PolicyDomain) Reset() {
	*x = PolicyDomain{}
	mi := &file_aegis_v1_platform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDomain) ProtoMessage() {}

func (x *PolicyDomain) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDomain.ProtoReflect.Descriptor instead.
func (*PolicyDomain) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyDomain) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *PolicyDomain) GetDataLevel() string {
	if x != nil {
		return x.DataLevel
	}
	return ""
}

func (x *PolicyDomain) GetDenyEgressByDefault() bool {
	if x != nil {
		return x.DenyEgressByDefault
	}
	return false
}

type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	LimitUsd      float64                `protobuf:"fixed64,3,opt,name=limit_usd,json=limitUsd,proto3" json:"limit_usd,omitempty"`
	PolicyMode    string                 `protobuf:"bytes,4,opt,name=policy_mode,json=policyMode,proto3" json:"policy_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_aegis_v1_platform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{2}
}

func (x *Budget) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Budget) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Budget) GetLimitUsd() float64 {
	if x != nil {
		return x.LimitUsd
	}
	return 0
}

func (x *Budget) GetPolicyMode() string {
	if x != nil {
		return x.PolicyMode
	}
	return ""
}

type Flavor struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chip               string                 `protobuf:"bytes,2,opt,name=chip,proto3" json:"chip,omitempty"`
	MigProfile         string                 `protobuf:"bytes,3,opt,name=mig_profile,json=migProfile,proto3" json:"mig_profile,omitempty"`
	RdmaRequired       bool                   `protobuf:"varint,4,opt,name=rdma_required,json=rdmaRequired,proto3" json:"rdma_required,omitempty"`
	ResourceName       string                 `protobuf:"bytes,5,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	GpuCount           int32                  `protobuf:"varint,6,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	MemoryGib          float64                `protobuf:"fixed64,7,opt,name=memory_gib,json=memoryGib,proto3" json:"memory_gib,omitempty"`
	PriceUsdPerGpuHour float64                `protobuf:"fixed64,8,opt,name=price_usd_per_gpu_hour,json=priceUsdPerGpuHour,proto3" json:"price_usd_per_gpu_hour,omitempty"`
	// Optional CPU request expressed in Kubernetes quantity format, e.g. "1" or "500m".
	CpuCoresRequest string `protobuf:"bytes,9,opt,name=cpu_cores_request,json=cpuCoresRequest,proto3" json:"cpu_cores_request,omitempty"`
	// Optional memory request expressed in Kubernetes quantity format, e.g. "4Gi" or "1024Mi".
	MemoryRequest string `protobuf:"bytes,10,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flavor) Reset() {
	*x = Flavor{}
	mi := &file_aegis_v1_platform_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flavor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flavor) ProtoMessage() {}

func (x *Flavor) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flavor.ProtoReflect.Descriptor instead.
func (*Flavor) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{3}
}

func (x *Flavor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flavor) GetChip() string {
	if x != nil {
		return x.Chip
	}
	return ""
}

func (x *Flavor) GetMigProfile() string {
	if x != nil {
		return x.MigProfile
	}
	return ""
}

func (x *Flavor) GetRdmaRequired() bool {
	if x != nil {
		return x.RdmaRequired
	}
	return false
}

func (x *Flavor) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *Flavor) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *Flavor) GetMemoryGib() float64 {
	if x != nil {
		return x.MemoryGib
	}
	return 0
}

func (x *Flavor) GetPriceUsdPerGpuHour() float64 {
	if x != nil {
		return x.PriceUsdPerGpuHour
	}
	return 0
}

func (x *Flavor) GetCpuCoresRequest() string {
	if x != nil {
		return x.CpuCoresRequest
	}
	return ""
}

func (x *Flavor) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

type Queue struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Name                      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProjectId                 string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	PriorityTier              string                 `protobuf:"bytes,3,opt,name=priority_tier,json=priorityTier,proto3" json:"priority_tier,omitempty"` // "prod"|"research"|"background"
	AllowedFlavors            []string               `protobuf:"bytes,4,rep,name=allowed_flavors,json=allowedFlavors,proto3" json:"allowed_flavors,omitempty"`
	DefaultMaxDurationSeconds int64                  `protobuf:"varint,5,opt,name=default_max_duration_seconds,json=defaultMaxDurationSeconds,proto3" json:"default_max_duration_seconds,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_aegis_v1_platform_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{4}
}

func (x *Queue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Queue) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Queue) GetPriorityTier() string {
	if x != nil {
		return x.PriorityTier
	}
	return ""
}

func (x *Queue) GetAllowedFlavors() []string {
	if x != nil {
		return x.AllowedFlavors
	}
	return nil
}

func (x *Queue) GetDefaultMaxDurationSeconds() int64 {
	if x != nil {
		return x.DefaultMaxDurationSeconds
	}
	return 0
}

// Workload
type WorkspaceSpec struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Flavor             string                 `protobuf:"bytes,1,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Image              string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Env                map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command            []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	MaxDurationSeconds int64                  `protobuf:"varint,5,opt,name=max_duration_seconds,json=maxDurationSeconds,proto3" json:"max_duration_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkspaceSpec) Reset() {
	*x = WorkspaceSpec{}
	mi := &file_aegis_v1_platform_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceSpec) ProtoMessage() {}

func (x *WorkspaceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceSpec.ProtoReflect.Descriptor instead.
func (*WorkspaceSpec) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{5}
}

func (x *WorkspaceSpec) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *WorkspaceSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *WorkspaceSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *WorkspaceSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *WorkspaceSpec) GetMaxDurationSeconds() int64 {
	if x != nil {
		return x.MaxDurationSeconds
	}
	return 0
}

type TrainingSpec struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Flavor             string                 `protobuf:"bytes,1,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Workers            int32                  `protobuf:"varint,2,opt,name=workers,proto3" json:"workers,omitempty"`
	GpusPerWorker      int32                  `protobuf:"varint,3,opt,name=gpus_per_worker,json=gpusPerWorker,proto3" json:"gpus_per_worker,omitempty"`
	Image              string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Command            []string               `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	Gang               bool                   `protobuf:"varint,6,opt,name=gang,proto3" json:"gang,omitempty"`
	MaxDurationSeconds int64                  `protobuf:"varint,7,opt,name=max_duration_seconds,json=maxDurationSeconds,proto3" json:"max_duration_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TrainingSpec) Reset() {
	*x = TrainingSpec{}
	mi := &file_aegis_v1_platform_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingSpec) ProtoMessage() {}

func (x *TrainingSpec) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingSpec.ProtoReflect.Descriptor instead.
func (*TrainingSpec) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{6}
}

func (x *TrainingSpec) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *TrainingSpec) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *TrainingSpec) GetGpusPerWorker() int32 {
	if x != nil {
		return x.GpusPerWorker
	}
	return 0
}

func (x *TrainingSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TrainingSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TrainingSpec) GetGang() bool {
	if x != nil {
		return x.Gang
	}
	return false
}

func (x *TrainingSpec) GetMaxDurationSeconds() int64 {
	if x != nil {
		return x.MaxDurationSeconds
	}
	return 0
}

type ResourceHints struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ResourceName string                 `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"` // e.g. "nvidia.com/mig-1g.10gb" or "nvidia.com/gpu"
	GpuCount     int32                  `protobuf:"varint,2,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`            // per container GPU count to request
	// Optional CPU core quantity expressed as a Kubernetes quantity string.
	CpuCoresRequest string `protobuf:"bytes,3,opt,name=cpu_cores_request,json=cpuCoresRequest,proto3" json:"cpu_cores_request,omitempty"`
	// Optional memory quantity expressed as a Kubernetes quantity string.
	MemoryRequest string `protobuf:"bytes,4,opt,name=memory_request,json=memoryRequest,proto3" json:"memory_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceHints) Reset() {
	*x = ResourceHints{}
	mi := &file_aegis_v1_platform_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceHints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceHints) ProtoMessage() {}

func (x *ResourceHints) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceHints.ProtoReflect.Descriptor instead.
func (*ResourceHints) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceHints) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *ResourceHints) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *ResourceHints) GetCpuCoresRequest() string {
	if x != nil {
		return x.CpuCoresRequest
	}
	return ""
}

func (x *ResourceHints) GetMemoryRequest() string {
	if x != nil {
		return x.MemoryRequest
	}
	return ""
}

type Workload struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Queue     string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	ClusterId string                 `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Status    string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Url       string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Workload_Workspace
	//	*Workload_Training
	Kind          isWorkload_Kind `protobuf_oneof:"kind"`
	Hints         *ResourceHints  `protobuf:"bytes,12,opt,name=hints,proto3" json:"hints,omitempty"`
	UiStatus      string          `protobuf:"bytes,13,opt,name=ui_status,json=uiStatus,proto3" json:"ui_status,omitempty"`
	Message       string          `protobuf:"bytes,14,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_aegis_v1_platform_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{8}
}

func (x *Workload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workload) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Workload) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Workload) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Workload) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Workload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Workload) GetKind() isWorkload_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Workload) GetWorkspace() *WorkspaceSpec {
	if x != nil {
		if x, ok := x.Kind.(*Workload_Workspace); ok {
			return x.Workspace
		}
	}
	return nil
}

func (x *Workload) GetTraining() *TrainingSpec {
	if x != nil {
		if x, ok := x.Kind.(*Workload_Training); ok {
			return x.Training
		}
	}
	return nil
}

func (x *Workload) GetHints() *ResourceHints {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *Workload) GetUiStatus() string {
	if x != nil {
		return x.UiStatus
	}
	return ""
}

func (x *Workload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type isWorkload_Kind interface {
	isWorkload_Kind()
}

type Workload_Workspace struct {
	Workspace *WorkspaceSpec `protobuf:"bytes,10,opt,name=workspace,proto3,oneof"`
}

type Workload_Training struct {
	Training *TrainingSpec `protobuf:"bytes,11,opt,name=training,proto3,oneof"`
}

func (*Workload_Workspace) isWorkload_Kind() {}

func (*Workload_Training) isWorkload_Kind() {}

// Cluster handshake
type ClusterRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	IlLevel       string                 `protobuf:"bytes,4,opt,name=il_level,json=ilLevel,proto3" json:"il_level,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterRegisterRequest) Reset() {
	*x = ClusterRegisterRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRegisterRequest) ProtoMessage() {}

func (x *ClusterRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRegisterRequest.ProtoReflect.Descriptor instead.
func (*ClusterRegisterRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{9}
}

func (x *ClusterRegisterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterRegisterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ClusterRegisterRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ClusterRegisterRequest) GetIlLevel() string {
	if x != nil {
		return x.IlLevel
	}
	return ""
}

func (x *ClusterRegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ClusterRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterRegisterResponse) Reset() {
	*x = ClusterRegisterResponse{}
	mi := &file_aegis_v1_platform_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterRegisterResponse) ProtoMessage() {}

func (x *ClusterRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterRegisterResponse.ProtoReflect.Descriptor instead.
func (*ClusterRegisterResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{10}
}

func (x *ClusterRegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ClusterRegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClusterHeartbeat struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClusterId        string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TtfGpuSecondsP50 float64                `protobuf:"fixed64,2,opt,name=ttf_gpu_seconds_p50,json=ttfGpuSecondsP50,proto3" json:"ttf_gpu_seconds_p50,omitempty"`
	AvailableFlavors []*Flavor              `protobuf:"bytes,3,rep,name=available_flavors,json=availableFlavors,proto3" json:"available_flavors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClusterHeartbeat) Reset() {
	*x = ClusterHeartbeat{}
	mi := &file_aegis_v1_platform_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterHeartbeat) ProtoMessage() {}

func (x *ClusterHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterHeartbeat.ProtoReflect.Descriptor instead.
func (*ClusterHeartbeat) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{11}
}

func (x *ClusterHeartbeat) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterHeartbeat) GetTtfGpuSecondsP50() float64 {
	if x != nil {
		return x.TtfGpuSecondsP50
	}
	return 0
}

func (x *ClusterHeartbeat) GetAvailableFlavors() []*Flavor {
	if x != nil {
		return x.AvailableFlavors
	}
	return nil
}

type ClusterHeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterHeartbeatAck) Reset() {
	*x = ClusterHeartbeatAck{}
	mi := &file_aegis_v1_platform_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterHeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterHeartbeatAck) ProtoMessage() {}

func (x *ClusterHeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterHeartbeatAck.ProtoReflect.Descriptor instead.
func (*ClusterHeartbeatAck) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{12}
}

func (x *ClusterHeartbeatAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Requests
type CreateProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{13}
}

func (x *CreateProjectRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type UpsertBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budget        *Budget                `protobuf:"bytes,1,opt,name=budget,proto3" json:"budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertBudgetRequest) Reset() {
	*x = UpsertBudgetRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBudgetRequest) ProtoMessage() {}

func (x *UpsertBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBudgetRequest.ProtoReflect.Descriptor instead.
func (*UpsertBudgetRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{14}
}

func (x *UpsertBudgetRequest) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type UpsertFlavorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flavor        *Flavor                `protobuf:"bytes,1,opt,name=flavor,proto3" json:"flavor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertFlavorRequest) Reset() {
	*x = UpsertFlavorRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertFlavorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertFlavorRequest) ProtoMessage() {}

func (x *UpsertFlavorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertFlavorRequest.ProtoReflect.Descriptor instead.
func (*UpsertFlavorRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{15}
}

func (x *UpsertFlavorRequest) GetFlavor() *Flavor {
	if x != nil {
		return x.Flavor
	}
	return nil
}

type UpsertQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertQueueRequest) Reset() {
	*x = UpsertQueueRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertQueueRequest) ProtoMessage() {}

func (x *UpsertQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertQueueRequest.ProtoReflect.Descriptor instead.
func (*UpsertQueueRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{16}
}

func (x *UpsertQueueRequest) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

type SubmitWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkloadRequest) Reset() {
	*x = SubmitWorkloadRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkloadRequest) ProtoMessage() {}

func (x *SubmitWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkloadRequest.ProtoReflect.Descriptor instead.
func (*SubmitWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{17}
}

func (x *SubmitWorkloadRequest) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

type GetWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadRequest) Reset() {
	*x = GetWorkloadRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadRequest) ProtoMessage() {}

func (x *GetWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{18}
}

func (x *GetWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWorkloadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsRequest) Reset() {
	*x = ListWorkloadsRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsRequest) ProtoMessage() {}

func (x *ListWorkloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkloadsRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{19}
}

func (x *ListWorkloadsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListWorkloadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Workload            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsResponse) Reset() {
	*x = ListWorkloadsResponse{}
	mi := &file_aegis_v1_platform_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsResponse) ProtoMessage() {}

func (x *ListWorkloadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkloadsResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{20}
}

func (x *ListWorkloadsResponse) GetItems() []*Workload {
	if x != nil {
		return x.Items
	}
	return nil
}

type LeaseWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseWorkloadRequest) Reset() {
	*x = LeaseWorkloadRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseWorkloadRequest) ProtoMessage() {}

func (x *LeaseWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseWorkloadRequest.ProtoReflect.Descriptor instead.
func (*LeaseWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{21}
}

func (x *LeaseWorkloadRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *LeaseWorkloadRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type LeaseWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Workload            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseWorkloadResponse) Reset() {
	*x = LeaseWorkloadResponse{}
	mi := &file_aegis_v1_platform_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseWorkloadResponse) ProtoMessage() {}

func (x *LeaseWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseWorkloadResponse.ProtoReflect.Descriptor instead.
func (*LeaseWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{22}
}

func (x *LeaseWorkloadResponse) GetItems() []*Workload {
	if x != nil {
		return x.Items
	}
	return nil
}

type AckWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Backend       string                 `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckWorkloadRequest) Reset() {
	*x = AckWorkloadRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckWorkloadRequest) ProtoMessage() {}

func (x *AckWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckWorkloadRequest.ProtoReflect.Descriptor instead.
func (*AckWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{23}
}

func (x *AckWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AckWorkloadRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AckWorkloadRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AckWorkloadRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type AckWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckWorkloadResponse) Reset() {
	*x = AckWorkloadResponse{}
	mi := &file_aegis_v1_platform_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckWorkloadResponse) ProtoMessage() {}

func (x *AckWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckWorkloadResponse.ProtoReflect.Descriptor instead.
func (*AckWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{24}
}

func (x *AckWorkloadResponse) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

type StartWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkloadRequest) Reset() {
	*x = StartWorkloadRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkloadRequest) ProtoMessage() {}

func (x *StartWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkloadRequest.ProtoReflect.Descriptor instead.
func (*StartWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{25}
}

func (x *StartWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartWorkloadRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type StartWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkloadResponse) Reset() {
	*x = StartWorkloadResponse{}
	mi := &file_aegis_v1_platform_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkloadResponse) ProtoMessage() {}

func (x *StartWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkloadResponse.ProtoReflect.Descriptor instead.
func (*StartWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{26}
}

func (x *StartWorkloadResponse) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

type GetBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetRequest) Reset() {
	*x = GetBudgetRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetRequest) ProtoMessage() {}

func (x *GetBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{27}
}

func (x *GetBudgetRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetBudgetRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type BudgetUsage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActualUsd      float64                `protobuf:"fixed64,1,opt,name=actual_usd,json=actualUsd,proto3" json:"actual_usd,omitempty"`
	ReservedUsd    float64                `protobuf:"fixed64,2,opt,name=reserved_usd,json=reservedUsd,proto3" json:"reserved_usd,omitempty"`
	RemainingUsd   float64                `protobuf:"fixed64,3,opt,name=remaining_usd,json=remainingUsd,proto3" json:"remaining_usd,omitempty"`
	PeriodStartUtc string                 `protobuf:"bytes,4,opt,name=period_start_utc,json=periodStartUtc,proto3" json:"period_start_utc,omitempty"`
	PeriodEndUtc   string                 `protobuf:"bytes,5,opt,name=period_end_utc,json=periodEndUtc,proto3" json:"period_end_utc,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BudgetUsage) Reset() {
	*x = BudgetUsage{}
	mi := &file_aegis_v1_platform_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetUsage) ProtoMessage() {}

func (x *BudgetUsage) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetUsage.ProtoReflect.Descriptor instead.
func (*BudgetUsage) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{28}
}

func (x *BudgetUsage) GetActualUsd() float64 {
	if x != nil {
		return x.ActualUsd
	}
	return 0
}

func (x *BudgetUsage) GetReservedUsd() float64 {
	if x != nil {
		return x.ReservedUsd
	}
	return 0
}

func (x *BudgetUsage) GetRemainingUsd() float64 {
	if x != nil {
		return x.RemainingUsd
	}
	return 0
}

func (x *BudgetUsage) GetPeriodStartUtc() string {
	if x != nil {
		return x.PeriodStartUtc
	}
	return ""
}

func (x *BudgetUsage) GetPeriodEndUtc() string {
	if x != nil {
		return x.PeriodEndUtc
	}
	return ""
}

type GetBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budget        *Budget                `protobuf:"bytes,1,opt,name=budget,proto3" json:"budget,omitempty"`
	Usage         *BudgetUsage           `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetResponse) Reset() {
	*x = GetBudgetResponse{}
	mi := &file_aegis_v1_platform_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetResponse) ProtoMessage() {}

func (x *GetBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetResponse.ProtoReflect.Descriptor instead.
func (*GetBudgetResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{29}
}

func (x *GetBudgetResponse) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *GetBudgetResponse) GetUsage() *BudgetUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ListBudgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetsRequest) Reset() {
	*x = ListBudgetsRequest{}
	mi := &file_aegis_v1_platform_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetsRequest) ProtoMessage() {}

func (x *ListBudgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetsRequest.ProtoReflect.Descriptor instead.
func (*ListBudgetsRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{30}
}

func (x *ListBudgetsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type BudgetWithUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budget        *Budget                `protobuf:"bytes,1,opt,name=budget,proto3" json:"budget,omitempty"`
	Usage         *BudgetUsage           `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetWithUsage) Reset() {
	*x = BudgetWithUsage{}
	mi := &file_aegis_v1_platform_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetWithUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetWithUsage) ProtoMessage() {}

func (x *BudgetWithUsage) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetWithUsage.ProtoReflect.Descriptor instead.
func (*BudgetWithUsage) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{31}
}

func (x *BudgetWithUsage) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *BudgetWithUsage) GetUsage() *BudgetUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ListBudgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BudgetWithUsage     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetsResponse) Reset() {
	*x = ListBudgetsResponse{}
	mi := &file_aegis_v1_platform_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetsResponse) ProtoMessage() {}

func (x *ListBudgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_platform_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetsResponse.ProtoReflect.Descriptor instead.
func (*ListBudgetsResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_platform_proto_rawDescGZIP(), []int{32}
}

func (x *ListBudgetsResponse) GetItems() []*BudgetWithUsage {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_aegis_v1_platform_proto protoreflect.FileDescriptor

const file_aegis_v1_platform_proto_rawDesc = "" +
	"\n" +
	"\x17aegis/v1/platform.proto\x12\baegis.v1\"\x8d\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\vowner_group\x18\x03 \x01(\tR\n" +
	"ownerGroup\x12.\n" +
	"\x06policy\x18\x04 \x01(\v2\x16.aegis.v1.PolicyDomainR\x06policy\"|\n" +
	"\fPolicyDomain\x12\x18\n" +
	"\aregions\x18\x01 \x03(\tR\aregions\x12\x1d\n" +
	"\n" +
	"data_level\x18\x02 \x01(\tR\tdataLevel\x123\n" +
	"\x16deny_egress_by_default\x18\x03 \x01(\bR\x13denyEgressByDefault\"{\n" +
	"\x06Budget\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1b\n" +
	"\tlimit_usd\x18\x03 \x01(\x01R\blimitUsd\x12\x1f\n" +
	"\vpolicy_mode\x18\x04 \x01(\tR\n" +
	"policyMode\"\xde\x02\n" +
	"\x06Flavor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04chip\x18\x02 \x01(\tR\x04chip\x12\x1f\n" +
	"\vmig_profile\x18\x03 \x01(\tR\n" +
	"migProfile\x12#\n" +
	"\rrdma_required\x18\x04 \x01(\bR\frdmaRequired\x12#\n" +
	"\rresource_name\x18\x05 \x01(\tR\fresourceName\x12\x1b\n" +
	"\tgpu_count\x18\x06 \x01(\x05R\bgpuCount\x12\x1d\n" +
	"\n" +
	"memory_gib\x18\a \x01(\x01R\tmemoryGib\x122\n" +
	"\x16price_usd_per_gpu_hour\x18\b \x01(\x01R\x12priceUsdPerGpuHour\x12*\n" +
	"\x11cpu_cores_request\x18\t \x01(\tR\x0fcpuCoresRequest\x12%\n" +
	"\x0ememory_request\x18\n" +
	" \x01(\tR\rmemoryRequest\"\xc9\x01\n" +
	"\x05Queue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12#\n" +
	"\rpriority_tier\x18\x03 \x01(\tR\fpriorityTier\x12'\n" +
	"\x0fallowed_flavors\x18\x04 \x03(\tR\x0eallowedFlavors\x12?\n" +
	"\x1cdefault_max_duration_seconds\x18\x05 \x01(\x03R\x19defaultMaxDurationSeconds\"\xf5\x01\n" +
	"\rWorkspaceSpec\x12\x16\n" +
	"\x06flavor\x18\x01 \x01(\tR\x06flavor\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x122\n" +
	"\x03env\x18\x03 \x03(\v2 .aegis.v1.WorkspaceSpec.EnvEntryR\x03env\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x120\n" +
	"\x14max_duration_seconds\x18\x05 \x01(\x03R\x12maxDurationSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x01\n" +
	"\fTrainingSpec\x12\x16\n" +
	"\x06flavor\x18\x01 \x01(\tR\x06flavor\x12\x18\n" +
	"\aworkers\x18\x02 \x01(\x05R\aworkers\x12&\n" +
	"\x0fgpus_per_worker\x18\x03 \x01(\x05R\rgpusPerWorker\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x05 \x03(\tR\acommand\x12\x12\n" +
	"\x04gang\x18\x06 \x01(\bR\x04gang\x120\n" +
	"\x14max_duration_seconds\x18\a \x01(\x03R\x12maxDurationSeconds\"\xa4\x01\n" +
	"\rResourceHints\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12\x1b\n" +
	"\tgpu_count\x18\x02 \x01(\x05R\bgpuCount\x12*\n" +
	"\x11cpu_cores_request\x18\x03 \x01(\tR\x0fcpuCoresRequest\x12%\n" +
	"\x0ememory_request\x18\x04 \x01(\tR\rmemoryRequest\"\xf5\x02\n" +
	"\bWorkload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x127\n" +
	"\tworkspace\x18\n" +
	" \x01(\v2\x17.aegis.v1.WorkspaceSpecH\x00R\tworkspace\x124\n" +
	"\btraining\x18\v \x01(\v2\x16.aegis.v1.TrainingSpecH\x00R\btraining\x12-\n" +
	"\x05hints\x18\f \x01(\v2\x17.aegis.v1.ResourceHintsR\x05hints\x12\x1b\n" +
	"\tui_status\x18\r \x01(\tR\buiStatus\x12\x18\n" +
	"\amessage\x18\x0e \x01(\tR\amessageB\x06\n" +
	"\x04kind\"\x87\x02\n" +
	"\x16ClusterRegisterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x19\n" +
	"\bil_level\x18\x04 \x01(\tR\ailLevel\x12D\n" +
	"\x06labels\x18\x05 \x03(\v2,.aegis.v1.ClusterRegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x17ClusterRegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9f\x01\n" +
	"\x10ClusterHeartbeat\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12-\n" +
	"\x13ttf_gpu_seconds_p50\x18\x02 \x01(\x01R\x10ttfGpuSecondsP50\x12=\n" +
	"\x11available_flavors\x18\x03 \x03(\v2\x10.aegis.v1.FlavorR\x10availableFlavors\"%\n" +
	"\x13ClusterHeartbeatAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"C\n" +
	"\x14CreateProjectRequest\x12+\n" +
	"\aproject\x18\x01 \x01(\v2\x11.aegis.v1.ProjectR\aproject\"?\n" +
	"\x13UpsertBudgetRequest\x12(\n" +
	"\x06budget\x18\x01 \x01(\v2\x10.aegis.v1.BudgetR\x06budget\"?\n" +
	"\x13UpsertFlavorRequest\x12(\n" +
	"\x06flavor\x18\x01 \x01(\v2\x10.aegis.v1.FlavorR\x06flavor\";\n" +
	"\x12UpsertQueueRequest\x12%\n" +
	"\x05queue\x18\x01 \x01(\v2\x0f.aegis.v1.QueueR\x05queue\"G\n" +
	"\x15SubmitWorkloadRequest\x12.\n" +
	"\bworkload\x18\x01 \x01(\v2\x12.aegis.v1.WorkloadR\bworkload\"$\n" +
	"\x12GetWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x14ListWorkloadsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"A\n" +
	"\x15ListWorkloadsResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.aegis.v1.WorkloadR\x05items\"G\n" +
	"\x14LeaseWorkloadRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"A\n" +
	"\x15LeaseWorkloadResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.aegis.v1.WorkloadR\x05items\"h\n" +
	"\x12AckWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend\"E\n" +
	"\x13AckWorkloadResponse\x12.\n" +
	"\bworkload\x18\x01 \x01(\v2\x12.aegis.v1.WorkloadR\bworkload\"E\n" +
	"\x14StartWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\"G\n" +
	"\x15StartWorkloadResponse\x12.\n" +
	"\bworkload\x18\x01 \x01(\v2\x12.aegis.v1.WorkloadR\bworkload\"G\n" +
	"\x10GetBudgetRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\"\xc4\x01\n" +
	"\vBudgetUsage\x12\x1d\n" +
	"\n" +
	"actual_usd\x18\x01 \x01(\x01R\tactualUsd\x12!\n" +
	"\freserved_usd\x18\x02 \x01(\x01R\vreservedUsd\x12#\n" +
	"\rremaining_usd\x18\x03 \x01(\x01R\fremainingUsd\x12(\n" +
	"\x10period_start_utc\x18\x04 \x01(\tR\x0eperiodStartUtc\x12$\n" +
	"\x0eperiod_end_utc\x18\x05 \x01(\tR\fperiodEndUtc\"j\n" +
	"\x11GetBudgetResponse\x12(\n" +
	"\x06budget\x18\x01 \x01(\v2\x10.aegis.v1.BudgetR\x06budget\x12+\n" +
	"\x05usage\x18\x02 \x01(\v2\x15.aegis.v1.BudgetUsageR\x05usage\"3\n" +
	"\x12ListBudgetsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"h\n" +
	"\x0fBudgetWithUsage\x12(\n" +
	"\x06budget\x18\x01 \x01(\v2\x10.aegis.v1.BudgetR\x06budget\x12+\n" +
	"\x05usage\x18\x02 \x01(\v2\x15.aegis.v1.BudgetUsageR\x05usage\"F\n" +
	"\x13ListBudgetsResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.aegis.v1.BudgetWithUsageR\x05items2\x8f\b\n" +
	"\rAegisPlatform\x12B\n" +
	"\rCreateProject\x12\x1e.aegis.v1.CreateProjectRequest\x1a\x11.aegis.v1.Project\x12?\n" +
	"\fUpsertBudget\x12\x1d.aegis.v1.UpsertBudgetRequest\x1a\x10.aegis.v1.Budget\x12D\n" +
	"\tGetBudget\x12\x1a.aegis.v1.GetBudgetRequest\x1a\x1b.aegis.v1.GetBudgetResponse\x12J\n" +
	"\vListBudgets\x12\x1c.aegis.v1.ListBudgetsRequest\x1a\x1d.aegis.v1.ListBudgetsResponse\x12?\n" +
	"\fUpsertFlavor\x12\x1d.aegis.v1.UpsertFlavorRequest\x1a\x10.aegis.v1.Flavor\x12<\n" +
	"\vUpsertQueue\x12\x1c.aegis.v1.UpsertQueueRequest\x1a\x0f.aegis.v1.Queue\x12E\n" +
	"\x0eSubmitWorkload\x12\x1f.aegis.v1.SubmitWorkloadRequest\x1a\x12.aegis.v1.Workload\x12?\n" +
	"\vGetWorkload\x12\x1c.aegis.v1.GetWorkloadRequest\x1a\x12.aegis.v1.Workload\x12P\n" +
	"\rListWorkloads\x12\x1e.aegis.v1.ListWorkloadsRequest\x1a\x1f.aegis.v1.ListWorkloadsResponse\x12P\n" +
	"\rLeaseWorkload\x12\x1e.aegis.v1.LeaseWorkloadRequest\x1a\x1f.aegis.v1.LeaseWorkloadResponse\x12P\n" +
	"\rStartWorkload\x12\x1e.aegis.v1.StartWorkloadRequest\x1a\x1f.aegis.v1.StartWorkloadResponse\x12J\n" +
	"\vAckWorkload\x12\x1c.aegis.v1.AckWorkloadRequest\x1a\x1d.aegis.v1.AckWorkloadResponse\x12V\n" +
	"\x0fRegisterCluster\x12 .aegis.v1.ClusterRegisterRequest\x1a!.aegis.v1.ClusterRegisterResponse\x12F\n" +
	"\tHeartbeat\x12\x1a.aegis.v1.ClusterHeartbeat\x1a\x1d.aegis.v1.ClusterHeartbeatAckB\x8f\x01\n" +
	"\fcom.aegis.v1B\rPlatformProtoP\x01Z/github.com/yourorg/aegis/proto/aegis/v1;aegisv1\xa2\x02\x03AXX\xaa\x02\bAegis.V1\xca\x02\bAegis\\V1\xe2\x02\x14Aegis\\V1\\GPBMetadata\xea\x02\tAegis::V1b\x06proto3"

var (
	file_aegis_v1_platform_proto_rawDescOnce sync.Once
	file_aegis_v1_platform_proto_rawDescData []byte
)

func file_aegis_v1_platform_proto_rawDescGZIP() []byte {
	file_aegis_v1_platform_proto_rawDescOnce.Do(func() {
		file_aegis_v1_platform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_platform_proto_rawDesc), len(file_aegis_v1_platform_proto_rawDesc)))
	})
	return file_aegis_v1_platform_proto_rawDescData
}

var file_aegis_v1_platform_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_aegis_v1_platform_proto_goTypes = []any{
	(*Project)(nil),                 // 0: aegis.v1.Project
	(*PolicyDomain)(nil),            // 1: aegis.v1.PolicyDomain
	(*Budget)(nil),                  // 2: aegis.v1.Budget
	(*Flavor)(nil),                  // 3: aegis.v1.Flavor
	(*Queue)(nil),                   // 4: aegis.v1.Queue
	(*WorkspaceSpec)(nil),           // 5: aegis.v1.WorkspaceSpec
	(*TrainingSpec)(nil),            // 6: aegis.v1.TrainingSpec
	(*ResourceHints)(nil),           // 7: aegis.v1.ResourceHints
	(*Workload)(nil),                // 8: aegis.v1.Workload
	(*ClusterRegisterRequest)(nil),  // 9: aegis.v1.ClusterRegisterRequest
	(*ClusterRegisterResponse)(nil), // 10: aegis.v1.ClusterRegisterResponse
	(*ClusterHeartbeat)(nil),        // 11: aegis.v1.ClusterHeartbeat
	(*ClusterHeartbeatAck)(nil),     // 12: aegis.v1.ClusterHeartbeatAck
	(*CreateProjectRequest)(nil),    // 13: aegis.v1.CreateProjectRequest
	(*UpsertBudgetRequest)(nil),     // 14: aegis.v1.UpsertBudgetRequest
	(*UpsertFlavorRequest)(nil),     // 15: aegis.v1.UpsertFlavorRequest
	(*UpsertQueueRequest)(nil),      // 16: aegis.v1.UpsertQueueRequest
	(*SubmitWorkloadRequest)(nil),   // 17: aegis.v1.SubmitWorkloadRequest
	(*GetWorkloadRequest)(nil),      // 18: aegis.v1.GetWorkloadRequest
	(*ListWorkloadsRequest)(nil),    // 19: aegis.v1.ListWorkloadsRequest
	(*ListWorkloadsResponse)(nil),   // 20: aegis.v1.ListWorkloadsResponse
	(*LeaseWorkloadRequest)(nil),    // 21: aegis.v1.LeaseWorkloadRequest
	(*LeaseWorkloadResponse)(nil),   // 22: aegis.v1.LeaseWorkloadResponse
	(*AckWorkloadRequest)(nil),      // 23: aegis.v1.AckWorkloadRequest
	(*AckWorkloadResponse)(nil),     // 24: aegis.v1.AckWorkloadResponse
	(*StartWorkloadRequest)(nil),    // 25: aegis.v1.StartWorkloadRequest
	(*StartWorkloadResponse)(nil),   // 26: aegis.v1.StartWorkloadResponse
	(*GetBudgetRequest)(nil),        // 27: aegis.v1.GetBudgetRequest
	(*BudgetUsage)(nil),             // 28: aegis.v1.BudgetUsage
	(*GetBudgetResponse)(nil),       // 29: aegis.v1.GetBudgetResponse
	(*ListBudgetsRequest)(nil),      // 30: aegis.v1.ListBudgetsRequest
	(*BudgetWithUsage)(nil),         // 31: aegis.v1.BudgetWithUsage
	(*ListBudgetsResponse)(nil),     // 32: aegis.v1.ListBudgetsResponse
	nil,                             // 33: aegis.v1.WorkspaceSpec.EnvEntry
	nil,                             // 34: aegis.v1.ClusterRegisterRequest.LabelsEntry
}
var file_aegis_v1_platform_proto_depIdxs = []int32{
	1,  // 0: aegis.v1.Project.policy:type_name -> aegis.v1.PolicyDomain
	33, // 1: aegis.v1.WorkspaceSpec.env:type_name -> aegis.v1.WorkspaceSpec.EnvEntry
	5,  // 2: aegis.v1.Workload.workspace:type_name -> aegis.v1.WorkspaceSpec
	6,  // 3: aegis.v1.Workload.training:type_name -> aegis.v1.TrainingSpec
	7,  // 4: aegis.v1.Workload.hints:type_name -> aegis.v1.ResourceHints
	34, // 5: aegis.v1.ClusterRegisterRequest.labels:type_name -> aegis.v1.ClusterRegisterRequest.LabelsEntry
	3,  // 6: aegis.v1.ClusterHeartbeat.available_flavors:type_name -> aegis.v1.Flavor
	0,  // 7: aegis.v1.CreateProjectRequest.project:type_name -> aegis.v1.Project
	2,  // 8: aegis.v1.UpsertBudgetRequest.budget:type_name -> aegis.v1.Budget
	3,  // 9: aegis.v1.UpsertFlavorRequest.flavor:type_name -> aegis.v1.Flavor
	4,  // 10: aegis.v1.UpsertQueueRequest.queue:type_name -> aegis.v1.Queue
	8,  // 11: aegis.v1.SubmitWorkloadRequest.workload:type_name -> aegis.v1.Workload
	8,  // 12: aegis.v1.ListWorkloadsResponse.items:type_name -> aegis.v1.Workload
	8,  // 13: aegis.v1.LeaseWorkloadResponse.items:type_name -> aegis.v1.Workload
	8,  // 14: aegis.v1.AckWorkloadResponse.workload:type_name -> aegis.v1.Workload
	8,  // 15: aegis.v1.StartWorkloadResponse.workload:type_name -> aegis.v1.Workload
	2,  // 16: aegis.v1.GetBudgetResponse.budget:type_name -> aegis.v1.Budget
	28, // 17: aegis.v1.GetBudgetResponse.usage:type_name -> aegis.v1.BudgetUsage
	2,  // 18: aegis.v1.BudgetWithUsage.budget:type_name -> aegis.v1.Budget
	28, // 19: aegis.v1.BudgetWithUsage.usage:type_name -> aegis.v1.BudgetUsage
	31, // 20: aegis.v1.ListBudgetsResponse.items:type_name -> aegis.v1.BudgetWithUsage
	13, // 21: aegis.v1.AegisPlatform.CreateProject:input_type -> aegis.v1.CreateProjectRequest
	14, // 22: aegis.v1.AegisPlatform.UpsertBudget:input_type -> aegis.v1.UpsertBudgetRequest
	27, // 23: aegis.v1.AegisPlatform.GetBudget:input_type -> aegis.v1.GetBudgetRequest
	30, // 24: aegis.v1.AegisPlatform.ListBudgets:input_type -> aegis.v1.ListBudgetsRequest
	15, // 25: aegis.v1.AegisPlatform.UpsertFlavor:input_type -> aegis.v1.UpsertFlavorRequest
	16, // 26: aegis.v1.AegisPlatform.UpsertQueue:input_type -> aegis.v1.UpsertQueueRequest
	17, // 27: aegis.v1.AegisPlatform.SubmitWorkload:input_type -> aegis.v1.SubmitWorkloadRequest
	18, // 28: aegis.v1.AegisPlatform.GetWorkload:input_type -> aegis.v1.GetWorkloadRequest
	19, // 29: aegis.v1.AegisPlatform.ListWorkloads:input_type -> aegis.v1.ListWorkloadsRequest
	21, // 30: aegis.v1.AegisPlatform.LeaseWorkload:input_type -> aegis.v1.LeaseWorkloadRequest
	25, // 31: aegis.v1.AegisPlatform.StartWorkload:input_type -> aegis.v1.StartWorkloadRequest
	23, // 32: aegis.v1.AegisPlatform.AckWorkload:input_type -> aegis.v1.AckWorkloadRequest
	9,  // 33: aegis.v1.AegisPlatform.RegisterCluster:input_type -> aegis.v1.ClusterRegisterRequest
	11, // 34: aegis.v1.AegisPlatform.Heartbeat:input_type -> aegis.v1.ClusterHeartbeat
	0,  // 35: aegis.v1.AegisPlatform.CreateProject:output_type -> aegis.v1.Project
	2,  // 36: aegis.v1.AegisPlatform.UpsertBudget:output_type -> aegis.v1.Budget
	29, // 37: aegis.v1.AegisPlatform.GetBudget:output_type -> aegis.v1.GetBudgetResponse
	32, // 38: aegis.v1.AegisPlatform.ListBudgets:output_type -> aegis.v1.ListBudgetsResponse
	3,  // 39: aegis.v1.AegisPlatform.UpsertFlavor:output_type -> aegis.v1.Flavor
	4,  // 40: aegis.v1.AegisPlatform.UpsertQueue:output_type -> aegis.v1.Queue
	8,  // 41: aegis.v1.AegisPlatform.SubmitWorkload:output_type -> aegis.v1.Workload
	8,  // 42: aegis.v1.AegisPlatform.GetWorkload:output_type -> aegis.v1.Workload
	20, // 43: aegis.v1.AegisPlatform.ListWorkloads:output_type -> aegis.v1.ListWorkloadsResponse
	22, // 44: aegis.v1.AegisPlatform.LeaseWorkload:output_type -> aegis.v1.LeaseWorkloadResponse
	26, // 45: aegis.v1.AegisPlatform.StartWorkload:output_type -> aegis.v1.StartWorkloadResponse
	24, // 46: aegis.v1.AegisPlatform.AckWorkload:output_type -> aegis.v1.AckWorkloadResponse
	10, // 47: aegis.v1.AegisPlatform.RegisterCluster:output_type -> aegis.v1.ClusterRegisterResponse
	12, // 48: aegis.v1.AegisPlatform.Heartbeat:output_type -> aegis.v1.ClusterHeartbeatAck
	35, // [35:49] is the sub-list for method output_type
	21, // [21:35] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_aegis_v1_platform_proto_init() }
func file_aegis_v1_platform_proto_init() {
	if File_aegis_v1_platform_proto != nil {
		return
	}
	file_aegis_v1_platform_proto_msgTypes[8].OneofWrappers = []any{
		(*Workload_Workspace)(nil),
		(*Workload_Training)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_platform_proto_rawDesc), len(file_aegis_v1_platform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v1_platform_proto_goTypes,
		DependencyIndexes: file_aegis_v1_platform_proto_depIdxs,
		MessageInfos:      file_aegis_v1_platform_proto_msgTypes,
	}.Build()
	File_aegis_v1_platform_proto = out.File
	file_aegis_v1_platform_proto_goTypes = nil
	file_aegis_v1_platform_proto_depIdxs = nil
}
