#!/bin/bash

# Aegis AWS Infrastructure - Complete Deployment
# Creates everything needed for cloud GPU testing
#
# Environment Variables:
#   AWS_PROFILE - AWS profile to use (default: aegis-new)
#   PLATFORM_API_ENDPOINT - Platform API gRPC endpoint (default: placeholder)
#
# Usage:
#   # Basic deployment with placeholder platform-api endpoint
#   ./scripts/deploy.sh
#
#   # Deployment with custom platform-api endpoint
#   PLATFORM_API_ENDPOINT="platform-api.example.com:8081" ./scripts/deploy.sh
#
# Note: This script automatically updates charts/aegis-spoke/values-cloud.yaml
# with the current infrastructure values (load balancer, ECR repos, etc.)

set -e

CLUSTER_NAME="aegis-spoke-prod"
REGION="us-east-1"
AWS_PROFILE="${AWS_PROFILE:-aegis-new}"
ACCOUNT_ID="195714074609"
PLATFORM_API_ENDPOINT="${PLATFORM_API_ENDPOINT:-YOUR_PLATFORM_API_ENDPOINT:8081}"

echo "🚀 Deploying Aegis to AWS"
echo "   - EKS Cluster: $CLUSTER_NAME"
echo "   - Region: $REGION"
echo "   - Account: $ACCOUNT_ID"
echo "   - Platform API: $PLATFORM_API_ENDPOINT"
echo ""

# Get AWS account ID
CURRENT_ACCOUNT=$(aws sts get-caller-identity --profile $AWS_PROFILE --query 'Account' --output text)
if [ "$CURRENT_ACCOUNT" != "$ACCOUNT_ID" ]; then
    echo "❌ Wrong AWS account. Expected $ACCOUNT_ID, got $CURRENT_ACCOUNT"
    exit 1
fi

echo "✅ AWS credentials verified"

# 1. Create ECR repositories
echo "🗂️  Creating ECR repositories..."
for repo in "aegis/k8s-agent" "aegis/proxy"; do
    aws ecr create-repository --repository-name "$repo" --region $REGION --profile $AWS_PROFILE 2>/dev/null || true
done

# 2. Skip Docker image building (images already exist in ECR)
echo "⏭️  Skipping Docker image build (using existing images in ECR)"

# 3. Create EKS cluster
echo "🏗️  Creating EKS cluster (15-20 minutes)..."
eksctl create cluster -f aegis-spoke-eks.yaml --profile $AWS_PROFILE

echo "✅ EKS cluster created"

# 4. Install NGINX Ingress Controller
echo "🌐 Installing NGINX Ingress Controller..."
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx --force-update
helm repo update
helm install ingress-nginx ingress-nginx/ingress-nginx -n kube-system

# Wait for load balancer
echo "⏳ Waiting for load balancer..."
kubectl wait --for=condition=available --timeout=300s deployment/ingress-nginx-controller -n kube-system

# Get load balancer URL
LB_HOSTNAME=$(kubectl get service ingress-nginx-controller -n kube-system -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
echo "🔗 Load Balancer: $LB_HOSTNAME"

# 5. Generate TLS certificates
echo "🔐 Generating TLS certificates..."
openssl req -x509 -newkey rsa:2048 -keyout /tmp/tls.key -out /tmp/tls.crt -days 365 -nodes -subj "/CN=aegis-proxy" >/dev/null 2>&1

# 6. Deploy Aegis Spoke
echo "📦 Deploying Aegis Spoke..."
kubectl create ns aegis-spoke || true

# Update values with load balancer hostname
sed -i.bak "s|hostname:.*|hostname: \"$LB_HOSTNAME\"|" charts/aegis-spoke/values-cloud.yaml

helm install aegis-spoke-aws charts/aegis-spoke \
    -n aegis-spoke \
    -f charts/aegis-spoke/values-cloud.yaml \
    --set-file proxy.tls.cert=/tmp/tls.crt \
    --set-file proxy.tls.key=/tmp/tls.key

# 7. Update values-cloud.yaml with dynamic infrastructure values
echo "🔧 Updating Helm values with infrastructure details..."

# Generate cluster ID from region and cluster name
CLUSTER_ID="aws-${REGION}-prod"

# Update values-cloud.yaml with actual infrastructure values
cat > charts/aegis-spoke/values-cloud.yaml << EOF
# Overrides for cloud / ingress-terminated TLS deployments.
# Auto-generated by deploy.sh on $(date)

k8sAgent:
  image:
    repository: ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/aegis/k8s-agent
    tag: "amd64"
  env:
    AEGIS_CLUSTER_ID: "${CLUSTER_ID}"
    # TODO: Update this to your actual platform-api endpoint when deployed to cloud
    # For local development, use: "host.docker.internal:8081"
    # For cloud deployment, use your platform-api service URL
    AEGIS_CP_GRPC: "${PLATFORM_API_ENDPOINT}"
    AEGIS_PROXY_INGRESS_HOST: "${LB_HOSTNAME}"

proxy:
  image:
    repository: ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/aegis/proxy
    tag: "amd64"
  ingress:
    hostname: "${LB_HOSTNAME}"
  tls:
    terminateAtIngress: true
EOF

echo "✅ Updated values-cloud.yaml with:"
echo "   - ECR repositories: ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
echo "   - Cluster ID: ${CLUSTER_ID}"
echo "   - Load Balancer: ${LB_HOSTNAME}"

# 8. Upgrade deployment with updated values
echo "🔄 Upgrading deployment with updated configuration..."
helm upgrade aegis-spoke-aws charts/aegis-spoke \
    -n aegis-spoke \
    -f charts/aegis-spoke/values-cloud.yaml \
    --set-file proxy.tls.cert=/tmp/tls.crt \
    --set-file proxy.tls.key=/tmp/tls.key

# 9. Wait for pods
echo "⏳ Waiting for pods to be ready..."
kubectl wait --for=condition=ready pod -l app.kubernetes.io/instance=aegis-spoke-aws -n aegis-spoke --timeout=300s

# 10. Scale down GPU nodes to save money
echo "💰 Scaling GPU nodes to 0 (cost optimization)..."
aws eks update-nodegroup-config \
    --cluster-name $CLUSTER_NAME \
    --nodegroup-name gpu-workers-g4 \
    --scaling-config minSize=0,maxSize=2,desiredSize=0 \
    --region $REGION --profile $AWS_PROFILE >/dev/null

echo ""
echo "🎉 Deployment complete!"
echo ""
echo "📊 Infrastructure Summary:"
echo "   - EKS Cluster: $CLUSTER_NAME (Kubernetes 1.33)"
echo "   - Proxy URL: http://$LB_HOSTNAME"
echo "   - Cluster ID: aws-us-east-1-prod"
echo "   - GPU Nodes: 0 (will auto-scale when needed)"
echo ""
echo "💰 Current Cost: ~$0.15/hour (control plane + load balancer)"
echo "💡 GPU cost: ~$1.50/hour when scaled up"
echo ""
echo "🔧 Configuration for platform-api:"
echo "   Cluster ID: aws-us-east-1-prod"
echo "   Proxy URL: http://$LB_HOSTNAME"
echo ""
echo "📝 Next steps:"
echo "   1. Update your platform-api to connect to: aws-us-east-1-prod"
echo "   2. Set AEGIS_CP_GRPC in k8s-agent to your platform-api endpoint"
echo "   3. Test GPU workload deployment from Aegis UI"