#!/usr/bin/env bash
set -euo pipefail

# Generate charts/aegis-spoke/values-aws-relay.yaml from terraform/pulumi-stack outputs.
# This avoids hard-coding the NLB endpoint; it reads the relay NLB + endpoints
# from Terraform state (terraform apply must have been run beforehand).
#
# Usage:
#   scripts/render-aws-relay-values.sh
#   # optional: AWS_PROFILE=... scripts/render-aws-relay-values.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${ROOT_DIR}/terraform/pulumi-stack"
OUT_FILE="${ROOT_DIR}/charts/aegis-spoke/values-aws-relay.yaml"

tf_out() {
  terraform -chdir="${TF_DIR}" output -raw "$1"
}

platform_ep="$(tf_out relay_platform_api_endpoint)"
keycloak_ep="$(tf_out relay_keycloak_endpoint)"
nlb_dns="$(tf_out relay_nlb_dns)"
public_ip="$(tf_out relay_public_ip)"

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

cat > "${OUT_FILE}" <<EOF
# Auto-generated by scripts/render-aws-relay-values.sh
# Generated at: ${timestamp}
#
# NLB DNS: ${nlb_dns}
# Platform API: ${platform_ep}
# Keycloak: ${keycloak_ep}
# Relay public IP (SSH tunnel target): ${public_ip}
#
# Usage:
#   helm upgrade aegis-spoke ./charts/aegis-spoke -n aegis-system \\
#     -f charts/aegis-spoke/values.yaml \\
#     -f charts/aegis-spoke/values-aws-relay.yaml \\
#     --set k8sAgent.env.AEGIS_CLUSTER_ID=<cluster-id> \\
#     --set k8sAgent.env.AEGIS_REGION=us-east-1 \\
#     --set k8sAgent.env.AEGIS_PROVIDER=aws

k8sAgent:
  image:
    pullPolicy: Always
    tag: "dev"
  env:
    # gRPC to platform-api via AWS NLB (TCP passthrough, preserves HTTP/2)
    AEGIS_CP_GRPC: "${platform_ep}"
    AEGIS_CP_GRPC_INSECURE: "false"
    AEGIS_CP_GRPC_SKIP_VERIFY: "true"
    AEGIS_CP_GRPC_SERVER_NAME: ""
    AEGIS_FLAVORS: "cpu-small,t4-1gpu"
    AEGIS_DEFAULT_IMAGE: "docker.io/carlosmsanchez/aegis-workspace-vscode:latest"

    # OIDC client credentials (Keycloak via AWS NLB)
    AEGIS_CP_OIDC_TOKEN_URL: "https://${keycloak_ep}/realms/aegis/protocol/openid-connect/token"
    AEGIS_CP_OIDC_CLIENT_ID: "spoke-agent"
    AEGIS_CP_OIDC_CLIENT_SECRET: "rEC99sBBWQAbRgg0xRQFBsMC8rt6pZOB"
    AEGIS_CP_OIDC_AUDIENCE: "aegis-platform"
    AEGIS_CP_OIDC_SKIP_TLS_VERIFY: "true"

    # Skip CA verification (self-signed certs through tunnel)
    AEGIS_PLATFORM_CA_B64: ""
    AEGIS_CP_OIDC_CA_B64: ""

proxy:
  enabled: false
EOF

echo "Rendered ${OUT_FILE} from terraform outputs."
