{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis-spoke.proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aegis-spoke.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  {{- with .Values.proxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    {{- include "aegis-spoke.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  ports:
    - name: https-proxy
      port: {{ .Values.proxy.service.port }}
      protocol: TCP
      targetPort: 8080
      {{- if and (eq .Values.proxy.service.type "NodePort") .Values.proxy.service.nodePort }}
      nodePort: {{ .Values.proxy.service.nodePort }}
      {{- end }}
{{- end }}
