# Overrides for local development.
k8sAgent:
  image:
    repository: aegis-k8s-agent-local
    tag: "latest"
    pullPolicy: IfNotPresent
  env:
    AEGIS_CLUSTER_ID: "dev-local"
    AEGIS_CP_GRPC: "aegis-services-platform-api.aegis-system.svc.cluster.local:8081"
    AEGIS_PROXY_INGRESS_HOST: "proxy.localtest.me"
    AEGIS_DEFAULT_IMAGE: "carlosmsanchez/aegis-workspace-vscode:latest"

proxy:
  enabled: false  # Use aegis-services proxy for local testing
  tls:
    terminateAtIngress: false  # Set to false to avoid cert validation
    cert: "dummy"
    key: "dummy"
